# Асинхронное выполнение кода (Корутины)

Соблазнительно думать, что порождение большего количества потоков может помочь нам выполнять больше задач одновременно. К сожалению, это не всегда так.

Создание слишком большого количества потоков может на самом деле сделать приложение неэффективным в некоторых ситуациях; потоки - это объекты, которые накладывают накладные расходы во время размещения объектов и сборки мусора.

Чтобы преодолеть эти проблемы, Kotlin представил новый способ написания асинхронного неблокирующего кода: Coroutine.

Подобно потокам, сопрограммы могут работать одновременно, ожидать и общаться друг с другом, с той разницей, что их создание намного дешевле, чем потоков.

Сопрограммы обеспечивают возможность избежать блокировки исполняющегося потока путём использования более дешёвой и управляемой операции: приостановки (suspend) сопрограммы.

Сопрограммы упрощают асинхронное программирование, оставив все осложнения внутри библиотек. Логика программы может быть выражена последовательно в сопрограммах, а базовая библиотека будет её реализовывать асинхронно. Библиотека может обернуть соответствующие части кода пользователя в обратные вызовы (callbacks), подписывающиеся на соответствующие события, и диспетчировать исполнение на различные потоки (или даже на разные машины!). Код при этом останется столь же простой, как если бы исполнялся строго последовательно.

Kotlin, как язык, предоставляет только минимальные низкоуровневые API в своей стандартной библиотеке, чтобы позволить различным другим библиотекам использовать сопрограммы. 

Для работы с корутинами сделана библиотека kotlinx.coroutines. Она содержит ряд высокоуровневых примитивов с поддержкой корутин, которые рассматриваются ниже, включая запуск, асинхронность и другие.

Для того, чтобы использовать биьблиотеку в своем проекте, необходимо добавить ее в зависимости:

```
//build.graddle
dependencies {
    ...
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.3'
}
```

## Основы

Здесь рассмотрим основные концепции.

### Наша первая корутина

Запустите следующий код:

```kt
import kotlinx.coroutines.*

fun main(){
    // запускает новую корутину в фоне и ПРОДОЛЖАЕТ выполнение
    GlobalScope.launch {
        // НЕ блокирующая задержака на 1 секунду
        delay(1_000L) 
        println("World!") 
    }
    // код в основном потоке продолжает выполняться
    println("Hello,")
    // БЛОКИРУЮЩАЯ задержка на 2 сек
    Thread.sleep(2_000L)
}
```

Увидим следующий результат:

```
Hello,
World! //выведет через секунду
```

По существу, корутины - это легкие потоки. Они запускаются с помощью launch coroutine builder в контексте некоторой области видимости Coroutine. Здесь мы запускаем новую сопрограмму в глобальной области, что означает, что время жизни новой сопрограммы ограничено только временем жизни всего приложения.

Аналогичный результат можно получить заменив *GlobalScope.launch { ... }* на *thread { ... }* и *delay(...)* на *Thread.sleep(...)* (в прошлой оекции мы именно это и делали).

Если попробовать использовать *delay(...)* в обычных потоках, то система выбросит исключение: Error: Kotlin: Suspend functions are only allowed to be called from a coroutine or another suspend function.

Это происходит потому, что *delay* это специальная *suspending function*, которая не блокирует поток, но приостанавливает корутину.

### Смешивание блокирующих и неблокирующих методов

В первом примере мы смешивали блокирующие и не-блокирующие задержки. Чтобы не запутаться какой вызов блокирующий, а какой нет, можно явно указать блокирующий вызов используя *runBlocking*:

```kt
import kotlinx.coroutines.*

fun main(){
    // запускает новую корутину в фоне и ПРОДОЛЖАЕТ выполнение
    GlobalScope.launch {
        // НЕ блокирующая задержака на 1 секунду
        delay(1_000L)
        println("World!")
    }
    // код в основном потоке продолжает выполняться
    println("Hello,")

    // это выражение блокирует основной поток 
    runBlocking {     
        delay(2_000L)
    }
}
```

Этот пример можно переписать по-другому:

```kt
fun main() = runBlocking<Unit> {
    GlobalScope.launch {
        delay(1000L)
        println("World!")
    }
    println("Hello,")
    delay(2000L)
}
```

Мы весь код функции пометили как блокирующий.

### Ожидание выполнения работы

Жесткое задание времени ожидания корутины плохая практика (нас извиняет что других способов мы пока не знаем).

Можно явно дождаться (не блокируя) завершения фонового задания:

```kt
fun main() = runBlocking<Unit> {
    val job = GlobalScope.launch {
        delay(1000L)
        println("World!")
    }
    println("Hello,")
    // ждем, пока выполнится корутина
    job.join()
}
```

Теперь функция завершится сразу, как только завершится корутина.

### Structured concurrency (упорядоченный параллелизм?)

Как бы ни мало процессорного времени занимали корутины, но все-равно они потребляют ресурсы (основного потока!), особенно если их много, а тем более если какие-то корутины из-за внутренних ошибок работают неправильно. Хранить ссылки на все корутины муторно и может привести к ошибкам.

Есть лучшее решение. Мы можем использовать *Structured concurrency* в нашем коде. Вместо того чтобы запускать сопрограммы в глобальной области, как мы обычно делаем с потоками (потоки всегда глобальны), мы можем запускать сопрограммы в конкретной области выполняемой нами операции.

В этом примере мы запускаем функцию *main* в корутине используя runBlocking Coroutine Builder (хз как это правильно перевести, строитель сопрограмм звучит криво). Каждый билдер добавляет CoroutineScope в область блока кода. Мы можем выполнять корутину без вызова метода *join*, т.к. внешняя корутина (runBlocking в нашем случае) не завершится, пока полностью не выполнится корутина запущенная в области. Т.о. мы можем упростить код:

```kt
fun main() = runBlocking<Unit> {//this: CoroutineScope
    launch {
        delay(1000L)
        println("World!")
    }
    println("Hello,")
    // убрали join
}
```

### Scope builder

В дополниние к областям предоставленным разными билдерами, мы можем объявить свою область, используя билдер coroutineScope. Он создает область и не завершает ее, пока не завершатся все вложенные корутины (дети).

*runBlocking* и *coroutineScope* выглядят похоже, т.к. обе ждут, пока не выполнится блок кода и вложенных детей. Основное отличие между ними в том, что *runBlocking* **блокирует** текущий поток, тогда как *coroutineScope* просто ожидает... 

```kt
fun main() = runBlocking<Unit> {
    launch {
        delay(200L)
        println("[${Thread.currentThread().name}] Task from runBlocking")
    }

    coroutineScope { // Creates a coroutine scope
        launch {
            delay(500L)
            println("[${Thread.currentThread().name}] Task from nested launch")
        }

        delay(100L)
        println("[${Thread.currentThread().name}] Task from coroutine scope") // This line will be printed before the nested launch
    }

    println("[${Thread.currentThread().name}] Coroutine scope is over")
}
```

```
[main] Task from coroutine scope
[main] Task from runBlocking
[main] Task from nested launch
[main] Coroutine scope is over
```

Обратите внимание, что сразу после сообщения "Task from coroutine scope", в ожидании вложенного запуска, выполняется и печатается "Task from runBlocking", хотя coroutineScope еще не завершен.

### Оформим код в функцию

Просто вынесем содержимое блока кода внутри *launch {...}* в отдельную функцию. Для этой функции указываем модификатор *suspend*. Suspending функция может быть использована внутри корутин как обычная функция, но в ней доступны дополнительные возможности, такие как вызов других *suspend* функций, например *delay*.

```kt
import kotlinx.coroutines.*

fun main() = runBlocking {
    launch { doWorld() }
    println("Hello,")
}

// это наша первая suspending функция
suspend fun doWorld() {
    delay(1000L)
    println("World!")
}
```

### Корутины ОЧЕНЬ легкие

Предлагается выполнить следующий код:

```kt
import kotlinx.coroutines.*

fun main() = runBlocking {
    repeat(100_000) { // launch a lot of coroutines
        launch {
            delay(1000L)
            print(".")
        }
    }
}
```

Выполнится за секунду. А если использовать обычные потоки, то скорее всего получим ошибку нехватки памяти.

### Глобальные корутины похожи на "демонов"

```kt
GlobalScope.launch {
    repeat(1000) { i ->
        println("I'm sleeping $i ...")
        delay(500L)
    }
}
delay(1300L) // just quit after delay
```

На выходе мы получим только 3 строки.

```
I'm sleeping 0 ...
I'm sleeping 1 ...
I'm sleeping 2 ...
```

Корутины запущенные в *GlobalScope* не препятсствуют завершению процесса. Этим они и похожи на "демонов".

## Прерывание работы и таймауты

### Прерывание работы корутины

Мы можем не дожидаться выполнения корутины и в любое время завершить ее вызвав методом *cancel()* (GlobalScope не указан, значит корутина не в режиме демона и не даст завершиться приложению, пока не доработает до конца)

```kt
fun main() = runBlocking<Unit> {
    val job = launch {
        repeat(1000) { i ->
            println("job: I'm sleeping $i ...")
            delay(500L)
        }
    }
    delay(1300L) // delay a bit
    println("main: I'm tired of waiting!")
    job.cancel() // cancels the job
    job.join() // waits for job's completion
    println("main: Now I can quit.")
}
```

```
job: I'm sleeping 0 ...
job: I'm sleeping 1 ...
job: I'm sleeping 2 ...
main: I'm tired of waiting!
main: Now I can quit.
```

> У класса *Job* есть еще метод *cancelAndJoin*

### Прерывания кооперативны

Это означает что ЛЮБАЯ корутина может быть прервана, но для этого она должна проверять свое состояние. Ниже приведен пример корутины, которая несмотря на вызов *cancelAndJoin* прервана не будет:

```kt
val startTime = System.currentTimeMillis()
val job = launch(Dispatchers.Default) {
    var nextPrintTime = startTime
    var i = 0
    while (i < 5) { // computation loop, just wastes CPU
        // print a message twice a second
        if (System.currentTimeMillis() >= nextPrintTime) {
            println("job: I'm sleeping ${i++} ...")
            nextPrintTime += 500L
        }
    }
}
delay(1300L) // delay a bit
println("main: I'm tired of waiting!")
job.cancelAndJoin() // cancels the job and waits for its completion
println("main: Now I can quit.")
```

### Делаем корутину прерываемой

Существует два способа. Первый что-то с yield, но примера нет. Второй - периодически проверять состояние прерывания:

Заменим проверку счетчика на проверку состояния (вообще это не хорошо, лучше бы обе проверки оставить...):

```kt
val startTime = System.currentTimeMillis()
val job = launch(Dispatchers.Default) {
    var nextPrintTime = startTime
    var i = 0
    while (isActive) { // cancellable computation loop
        // print a message twice a second
        if (System.currentTimeMillis() >= nextPrintTime) {
            println("job: I'm sleeping ${i++} ...")
            nextPrintTime += 500L
        }
    }
}
delay(1300L) // delay a bit
println("main: I'm tired of waiting!")
job.cancelAndJoin() // cancels the job and waits for its completion
println("main: Now I can quit.")
```

Свойство *isAlive* видно внутри корутины через объект CoroutineScope.

### Освобождайте ресурсы с помощью try .. finally

При прерывании корутины возникает исключение *CancellationException*, поэтому если есть какие-то открытые ресурсы, то их нужно завернуть в блок try .. finally (в примере ниже открытых ресурсов нет)

```kt
val job = launch {
    try {
        repeat(1000) { i ->
            println("job: I'm sleeping $i ...")
            delay(500L)
        }
    } finally {
        println("job: I'm running finally")
    }
}
delay(1300L) // delay a bit
println("main: I'm tired of waiting!")
job.cancelAndJoin() // cancels the job and waits for its completion
println("main: Now I can quit.")
```

И метод *join* и метод *cancelAndJoin* ждут завершения блока finally (в принципе это и так понятно - они ждут завершения ВСЕЙ корутины)

### Выполнение не прерываемого блока

Любая попытка использовать suspending функцию в блоке finally предыдущего примера вызывает исключение *CancellationException*, поскольку корутина, выполняющая этот код, в состоянии отмены. Как правило, это не проблема, так как все хорошо работающие операции закрытия (закрытие файла, отмена задания или закрытие любого канала связи) обычно не блокируются и не включают в себя какие-либо функции приостановки. Однако в редких случаях, когда вам нужно приостановить работу в отмененной корутине, вы можете обернуть соответствующий код в *withContext (Nonancellable) {...}* используя withContext функции и NonCancellable контекст, как показано в следующем примере:

```kt
val job = launch {
    try {
        repeat(1000) { i ->
            println("job: I'm sleeping $i ...")
            delay(500L)
        }
    } finally {
        withContext(NonCancellable) {
            println("job: I'm running finally")
            delay(1000L)
            println("job: And I've just delayed for 1 sec because I'm non-cancellable")
        }
    }
}
delay(1300L) // delay a bit
println("main: I'm tired of waiting!")
job.cancelAndJoin() // cancels the job and waits for its completion
println("main: Now I can quit.")
```

### Таймаут

Наиболее очевидная практическая причина отмены выполнения корутины заключается в том, что время ее выполнения превысило некоторый тайм-аут. В то время как вы можете вручную отслеживать ссылку на соответствующее задание и запускать отдельную корутину для отмены отслеживаемого после задержки, есть готовая к использованию функция withTimeout, которая делает это. Рассмотрим следующий пример:

```kt
withTimeout(1300L) {
    repeat(1000) { i ->
        println("I'm sleeping $i ...")
        delay(500L)
    }
}
```

Программа выдаст:

```
I'm sleeping 0 ...
I'm sleeping 1 ...
I'm sleeping 2 ...
Exception in thread "main" kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 1300 ms
```

Исключение *TimeoutCancellationException*, создаваемое *withTimeout*, является подклассом исключения *CancellationException*. Внутри отмененной сопрограммы исключение CancellationException считается нормальной причиной завершения сопрограммы. Однако в этом примере мы использовали withTimeout прямо внутри основной функции.

Поскольку отмена - это всего лишь исключение, все ресурсы закрываются обычным способом. Вы можете обернуть код с таймаутом в *try {...} catch (e: TimeoutCancellationException) {...}* блок, если необходимо выполнить какое-либо дополнительное действие специально для любого вида таймаута или использовать функцию withTimeoutOrNull, которая аналогична функции withTimeout, но возвращает значение null при таймауте, а не создает исключение:

```kt
val result = withTimeoutOrNull(1300L) {
    repeat(1000) { i ->
        println("I'm sleeping $i ...")
        delay(500L)
    }
    "Done" // will get cancelled before it produces this result
}
println("Result is $result")
```

```
I'm sleeping 0 ...
I'm sleeping 1 ...
I'm sleeping 2 ...
Result is null
```

## Составление Suspending функций

В этом разделе рассматриваются различные подходы к составлению *Suspending* функций.

### Последовательность действий по-умолчанию

Предположим, что у нас есть две *suspending* функции, которые делают что-то полезное, например, какой-то удаленный вызов службы или вычисление (в нашем примере каждая из них просто задерживается на секунду для примера):

```kt
suspend fun doSomethingUsefulOne(): Int {
    delay(1000L) // pretend we are doing something useful here
    return 13
}

suspend fun doSomethingUsefulTwo(): Int {
    delay(1000L) // pretend we are doing something useful here, too
    return 29
}
```

Мы используем обычный последовательный вызов, т.к. код в корутине, как и в обычном коде по умолчанию является последовательным. В следующем примере измеряется время, затраченное на работу корутин:

```kt
val time = measureTimeMillis {
    val one = doSomethingUsefulOne()
    val two = doSomethingUsefulTwo()
    println("The answer is ${one + two}")
}
println("Completed in $time ms")
```

Видно, что общее время работы примерно равно сумме времени работы каждой функции:

```
The answer is 42
Completed in 2017 ms
```

### Одновременный асинхронный запуск

Если выполнение функций не зависит друг от друга, то можно выполнить работу быстрее, запустив их одновременно. В этом нам поможет *async*.

Концептуально *async* - это то же самое, что и *launch*. Он запускает отдельную корутину, работающей одновременно со всеми другими корутинами. Разница в том, что *launch* возвращает *Job* и не несет никакого результирующего значения, в то время как *async* возвращает *Deffered* — легкое неблокирующее будущее, которое представляет собой обещание предоставить результат позже. Вы можете использовать метод *.await()* на отложенное значение, чтобы получить его конечный результат, но *Deffered* также является *Job*, поэтому вы можете отменить его при необходимости.

```kt
val time = measureTimeMillis {
    val one = async { doSomethingUsefulOne() }
    val two = async { doSomethingUsefulTwo() }
    println("The answer is ${one.await() + two.await()}")
}
println("Completed in $time ms")
```
По затраченному времени видно, что функции выполнялись параллельно и вся работа выполнена в два раза быстрее:

```
The answer is 42
Completed in 1017 ms
```

### Отложенный асинхронный запуск

При необходимости, мы можем создать асинхронный блок, но его реальный запуск отложить (задав параметр start = CoroutineStart.LAZY). В этом случае запуск производится методом *start*:

```kt
val time = measureTimeMillis {
    val one = async(start = CoroutineStart.LAZY) { doSomethingUsefulOne() }
    val two = async(start = CoroutineStart.LAZY) { doSomethingUsefulTwo() }
    // some computation
    one.start() // start the first one
    two.start() // start the second one
    println("The answer is ${one.await() + two.await()}")
}
println("Completed in $time ms")
```

Таким образом, здесь две корутины созданы, но не выполняются. Программист сам решает когда именно начать выполнение, вызывая start.

Обратите внимание, что если мы просто вызовем *await* в println без вызова start, это приведет к последовательному выполнению, так как await запускает выполнение корутины и ждет ее завершения.

### Асинхронные функции

Мы можем определить функции как асинхронные, используя async coroutine builder с явной ссылкой на GlobalScope. Мы называем такие функции с суффиксом "... Async", чтобы подчеркнуть тот факт, что они начинают асинхронные вычисления и нужно использовать полученное отложенное значение, чтобы получить результат.

```kt
// The result type of somethingUsefulOneAsync is Deferred<Int>
fun somethingUsefulOneAsync() = GlobalScope.async {
    doSomethingUsefulOne()
}

// The result type of somethingUsefulTwoAsync is Deferred<Int>
fun somethingUsefulTwoAsync() = GlobalScope.async {
    doSomethingUsefulTwo()
}
```

Обратите внимание, что эти функции xxxAsync не являются *suspend* функциями. Они могут быть использованы из любого места. Однако их использование всегда подразумевает асинхронное (здесь имеется в виду параллельное) выполнение с вызывающим кодом.

В следующем примере показано их использование за пределами корутин:

```kt
// note that we don't have `runBlocking` to the right of `main` in this example
fun main() {
    val time = measureTimeMillis {
        // we can initiate async actions outside of a coroutine
        val one = somethingUsefulOneAsync()
        val two = somethingUsefulTwoAsync()
        // but waiting for a result must involve either suspending or blocking.
        // here we use `runBlocking { ... }` to block the main thread while waiting for the result
        runBlocking {
            println("The answer is ${one.await() + two.await()}")
        }
    }
    println("Completed in $time ms")
}
```

Этот стиль программирования с асинхронными функциями приведен здесь только для иллюстрации, потому что это популярный стиль в других языках программирования. Использование этого стиля в Kotlin категорически не рекомендуется по причинам, описанным ниже.

Рассмотрим, что произойдет, если между строкой val one = somethingUsefulOneAsync() и выражением one.await() в коде возникает некоторая логическая ошибка, и программа выдает исключение, а операция, выполняемая программой, прерывается. Обычно глобальный обработчик ошибок может перехватывать это исключение, регистрировать и сообщать об ошибке разработчикам, но в противном случае программа может продолжать выполнять другие операции. Но здесь у нас есть somethingUsefulOneAsync, все еще работающее в фоновом режиме, хотя операция, которая его инициировала, была прервана. Эта проблема не возникает со структурированным параллелизмом, как показано в разделе ниже.

### Асинхронный структурированный параллелизм

Возьмем пример из [Одновременный асинхронный запуск](#Одновременный-асинхронный-запуск) и извлечем функцию, которая одновременно выполняет doSomethingUsefulOne и doSomethingUsefulTwo и возвращает сумму их результатов. Поскольку *async* coroutine builder определяется как расширение в CoroutineScope, нам необходимо иметь его в области видимости, и именно это обеспечивает функция coroutineScope:

```kt
suspend fun concurrentSum(): Int = coroutineScope {
    val one = async { doSomethingUsefulOne() }
    val two = async { doSomethingUsefulTwo() }
    one.await() + two.await()
}
```

Таким образом, если что-то пойдет не так в коде параллельной функции Sum и она выдаст исключение, все сопрограммы, запущенные в ее области видимости, будут отменены.

```kt
val time = measureTimeMillis {
    println("The answer is ${concurrentSum()}")
}
println("Completed in $time ms")
```

Операции по прежнему выполняются асинхронно:

```
The answer is 42
Completed in 1017 ms
```

Отмена всегда распространяется через иерархию корутин:

```kt
import kotlinx.coroutines.*

fun main() = runBlocking<Unit> {
    try {
        failedConcurrentSum()
    } catch(e: ArithmeticException) {
        println("Computation failed with ArithmeticException")
    }
}

suspend fun failedConcurrentSum(): Int = coroutineScope {
    val one = async<Int> { 
        try {
            delay(Long.MAX_VALUE) // Emulates very long computation
            42
        } finally {
            println("First child was cancelled")
        }
    }
    val two = async<Int> { 
        println("Second child throws an exception")
        throw ArithmeticException()
    }
    one.await() + two.await()
}
```

Обратите внимание, что и первый async (one) и ожидающий родитель (failedConcurrentSum) отменяются при сбое второго потомка:

```
Second child throws an exception
First child was cancelled
Computation failed with ArithmeticException
```

## Корутины: контекст и диспетчеры

Корутины всегда выполняются в некотором контексте, представленном значением типа *CoroutineContext*, определенного в стандартной библиотеке Kotlin.

Контекст корутины - это набор различных элементов. Основными элементами являются *Job*, которую мы видели ранее, и ее диспетчер, который рассматривается в этом разделе.

### Деспетчеры и потоки

Контекст корутины включает в себя [coroutine dispatcher](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-coroutine-dispatcher/index.html), который определяет, какой поток или потоки использует соответствующая корутина для своего выполнения. Диспетчер может ограничить выполнение корутины определенным потоком, отправить его в пул потоков или позволить ему работать неограниченно.

Все конструкторы корутин (coroutine builders), такие как launch и async, принимают необязательный параметр контекста сопрограммы, который можно использовать для явного указания диспетчера для новой корутины и других элементов контекста.

Попробуйте выполнить следующий пример:

```kt
import kotlinx.coroutines.*

fun main() = runBlocking<Unit> {
    launch { 
        // контекст родителя, main runBlocking
        println("main runBlocking      : I'm working in thread ${Thread.currentThread().name}")
    }
    launch(Dispatchers.Unconfined) { 
        // not confined - будет запущен в основном потоке
        println("Unconfined            : I'm working in thread ${Thread.currentThread().name}")
    }
    launch(Dispatchers.Default) { 
        // будет запущен в потоке DefaultDispatcher
        println("Default               : I'm working in thread ${Thread.currentThread().name}")
    }
    launch(newSingleThreadContext("MyOwnThread")) { 
        // запустся в созданном потоке
        println("newSingleThreadContext: I'm working in thread ${Thread.currentThread().name}")
    }
}
```

Получим примерно следующее (порядок может отличаться):

```
Unconfined            : I'm working in thread main
Default               : I'm working in thread DefaultDispatcher-worker-1
main runBlocking      : I'm working in thread main
newSingleThreadContext: I'm working in thread MyOwnThread
```

При запуске корутины без параметров (launch { ... }) наследуется текущий контекст (и его диспетчер) от CoroutineScope. В нашем случае она наследует контекст корутины main runBlocking, которая выполняется в главном потоке.

Dispatchers.Unconfined - это специальный диспетчер, который также работает в основном потоке, но на самом деле это другой механизм, который будет объяснен позже.

Диспетчер по умолчанию, используемый при запуске корутины в GlobalScope, представлен Dispatchers.Default и использует общий фоновый пул потоков, поэтому ``launch(Dispatchers.Default) { ... }`` использует тот же диспетчер, что и ``GlobalScope.launch { ... }``.

*newSingleThreadContext* создает поток для запуска сопрограммы. Выделенный поток - это очень дорогой ресурс. В реальном приложении он должен быть либо освобожден, когда больше не нужен, с помощью функции *close*, либо сохранен в переменной верхнего уровня и повторно использован в приложении.

### Неограниченный (Unconfined) и ограниченный (confined) деспетчер

Dispatchers.Unconfined запускает корутину в вызывающем потоке, но только до первой точки приостановки (suspend функции). После приостановки он возобновляет работу сопрограммы в потоке, который полностью определяется вызванной функцией приостановки. Неограниченный диспетчер подходит для корутин, которые не потребляют процессорное время и не обновляют общие данные (например, пользовательский интерфейс).

С другой стороны, диспетчер наследуется от CoroutineScope по умолчанию. Диспетчер по умолчанию для runBlocking, в частности, ограничен потоком вызова, поэтому его наследование приводит к ограничению выполнения этим потоком с предсказуемым расписанием FIFO.

```kt
launch(Dispatchers.Unconfined) { 
    // not confined -- will work with main thread
    println("Unconfined      : I'm working in thread ${Thread.currentThread().name}")
    delay(500)
    println("Unconfined      : After delay in thread ${Thread.currentThread().name}")
}
launch { 
    // context of the parent, main runBlocking coroutine
    println("main runBlocking: I'm working in thread ${Thread.currentThread().name}")
    delay(1000)
    println("main runBlocking: After delay in thread ${Thread.currentThread().name}")
}
```

Выведет следующее:

```
Unconfined      : I'm working in thread main
main runBlocking: I'm working in thread main
Unconfined      : After delay in thread kotlinx.coroutines.DefaultExecutor
main runBlocking: After delay in thread main
```

Итак, корутина с контекстом, унаследованным от runBlocking {...} продолжает выполняться в основном потоке, в то время как неограниченная возобновляется в потоке по умолчанию, который использует функция *delay*.

>Неограниченный диспетчер - это усовершенствованный механизм, который может быть полезен в некоторых случаях, ... . Неограниченный диспетчер не должен использоваться в общем коде.

### Отладка курутин и потоков

Корутины могут приостанавливаться в одном потоке и возобновляться в другом потоке. Даже с однопоточным диспетчером было бы трудно понять, что делает корутина, где и когда. Общий подход к отладке приложений с потоками заключается в печати имени потока в файле журнала для каждой записи. Эта функция повсеместно поддерживается фреймворками ведения журнала. При использовании корутин имя потока само по себе не дает большого контекста, поэтому kotlinx.coroutines включает средства отладки, чтобы сделать его проще.

Запустите следующий код с JVM опцией ``-Dkotlinx.coroutines.debug``:

```kt
val a = async {
    log("I'm computing a piece of the answer")
    6
}
val b = async {
    log("I'm computing another piece of the answer")
    7
}
log("The answer is ${a.await() * b.await()}")
```

Здесь у нас три корутины. Основная корутина (#1) внутри runBlocking и две корутины, вычисляющие отложенные значения a (#2) и b (#3). Все они выполняются в контексте runBlocking и ограничены основным потоком.

```
[main @coroutine#2] I'm computing a piece of the answer
[main @coroutine#3] I'm computing another piece of the answer
[main @coroutine#1] The answer is 42
```

Функция log выводит имя потока в квадратных скобках, и вы можете видеть, что это основной поток с добавленным к нему идентификатором текущей выполняемой корутины. Этот идентификатор последовательно присваивается всем созданным корутинам, когда включен режим отладки.

### Переключение между потоками

Выполните следующий код с опцией JVM ``-Dkotlinx.coroutines.debug``

```kt
newSingleThreadContext("Ctx1").use { ctx1 ->
    newSingleThreadContext("Ctx2").use { ctx2 ->
        runBlocking(ctx1) {
            log("Started in ctx1")
            withContext(ctx2) {
                log("Working in ctx2")
            }
            log("Back to ctx1")
        }
    }
}
```

Он демонстрирует несколько новых методов. Один из них использует *runBlocking* с явно заданным контекстом, а другой использует функцию *withContext* для изменения контекста корутины, оставаясь при этом в той же самой корутине, как вы можете видеть ниже:

```
[Ctx1 @coroutine#1] Started in ctx1
[Ctx2 @coroutine#1] Working in ctx2
[Ctx1 @coroutine#1] Back to ctx1
```

Обратите внимание, что в этом примере используется функция *use* из стандартной библиотеки Kotlin для освобождения потоков, созданных с помощью *newSingleThreadContext*.

### Job в контексте

Объект Job корутины является частью его контекста и может быть извлечено из него с помощью выражения ``coroutineContext[Job]``:

```kt
println("My job is ${coroutineContext[Job]}")
```




[1]: https://habr.com/ru/company/e-Legion/blog/442920/
